app/blueprints/problems/__init__.py
from flask import Blueprint
from flask_breadcrumbs import default_breadcrumb_root

problems = Blueprint('problems', __name__, template_folder='templates', static_folder='static', url_prefix='/problems')
default_breadcrumb_root(problems, '.')

from app.blueprints.problems import routes

app/blueprints/problems/routes.py
from flask import current_app as app
from flask import render_template, redirect, url_for, request, abort
from flask_login import current_user, login_required
from flask_breadcrumbs import register_breadcrumb
from sqlalchemy import desc

from app import db
from app.blueprints.problems import problems
from app.models import Grade, Topic, Submission
from app.contester.languages import languages
from app.utils.routes import grade_compliance_required, admin_required
from app.utils.db import get_task
import app.utils.breadcrumbs as bc


@problems.route('/redirect', methods=['GET'])
@login_required
def redirect_page():
    if current_user.is_admin:
        return redirect(url_for('problems.all_grades_page'))
    return redirect(url_for('problems.grade_page', grade_number=current_user.grade.number))


@problems.route('/', methods=['GET'])
@login_required
@admin_required
def all_grades_page():
    return render_template('problems/all_grades.html', title='Все классы', grades=db.session.query(Grade).all())


@problems.route('/grade-<int:grade_number>', methods=['GET'])
@register_breadcrumb(problems, '.grade', '', dynamic_list_constructor=bc.view_grade_dlc)
@login_required
@grade_compliance_required
def grade_page(grade_number):
    grade = db.session.query(Grade).filter(Grade.number == grade_number).first_or_404()
    topics = grade.topics.all()

    context = {
        'grade': grade,
        'topics': topics,
    }

    return render_template('problems/grade.html', title=f'{grade.number} класс', **context)


@problems.route('/grade-<int:grade_number>/<string:topic_translit_name>', methods=['GET'])
@register_breadcrumb(problems, '.grade.topic', '', dynamic_list_constructor=bc.view_topic_dlc)
@login_required
@grade_compliance_required
def topic_page(grade_number, topic_translit_name):
    grade = db.session.query(Grade).filter(Grade.number == grade_number).first_or_404()
    topic = db.session.query(Topic).filter(Topic.translit_name == topic_translit_name).first_or_404()
    tasks = topic.tasks.all()
    print(tasks)

    context = {
        'grade': grade,
        'topic': topic,
        'tasks': tasks
    }
    return render_template('problems/topic.html', title=topic.name, **context)


@problems.route(
    '/grade-<int:grade_number>/<string:topic_translit_name>/<string:task_translit_name>',
    defaults={'tab': 'problem'},
    methods=['GET']
)
@problems.route(
    '/grade-<int:grade_number>/<string:topic_translit_name>/<string:task_translit_name>/<string:tab>',
    methods=['GET']
)
@register_breadcrumb(problems, '.grade.topic.task', '', dynamic_list_constructor=bc.view_task_dlc)
@login_required
@grade_compliance_required
def task_page(grade_number, topic_translit_name, task_translit_name, tab):
    task = get_task(grade_number, topic_translit_name, task_translit_name)
    topic = task.topic

    global_context = {
        'task': task,
        'topic': topic,
    }

    page = request.args.get('table_page', type=int, default=1)

    if tab == 'problem':
        # Tab with problem (name, condition, editor etc)
        local_context = {
            'language_dict': languages.dictionary
        }
        return render_template(
            'problems/tabs/problem.html',
            title=f'{task.name} - Задача',
            **global_context,
            **local_context
        )

    elif tab == 'submissions':
        # Tab with user's submissions
        local_context = {
            'submissions': current_user.submissions.filter(
                Submission.task_id == task.id
            ).paginate(
                per_page=app.config['RECORDS_PER_PAGE'], page=page, error_out=False
            )
        }
        return render_template(
            'problems/tabs/submissions.html',
            title=f'{task.name} - Мои отправки',
            **global_context,
            **local_context
        )

    elif tab == 'all-submissions':
        # Tab with all submissions
        if current_user.is_admin:
            local_context = {
                'submissions': task.submissions.order_by(
                    desc(Submission.submission_date)
                ).paginate(
                    per_page=app.config['RECORDS_PER_PAGE'], page=page, error_out=False
                ),
                'show_users': True
            }
            return render_template(
                'problems/tabs/all_submissions.html',
                title=f'{task.name} - Все отправки',
                **global_context,
                **local_context
            )

        abort(403)

    abort(404)

app/blueprints/problems/templates/problems/all_grades.html
{% extends "base.html" %}

{% block css %}
    <link rel="stylesheet" href="{{ url_for('problems.static', filename='css/route.css') }}">
{% endblock %}

{% block content %}
    <div class="container-fluid">
        <div class="row">
            <div class="route__body">
                <div class="route__title text_with_icon">
                    <i class="fa fa-2x fa-tasks route__title__icon" aria-hidden="true"></i>
                    <p class="route__title__text">Классы:</p>
                </div>
                {% if grades %}
                    <div class="route__body_list box-shadow">
                        {% for grade in grades %}
                            <div class="list_item">
                                <a href="{{ url_for('problems.grade_page', grade_number=grade.number) }}"
                                   class="list_item__link"></a>
                                <div class="list_item_content">
                                    <p class="item_title">{{ grade.number }} класс</p>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                {% else %}
                    {% include 'responses/empty_response.html' %}
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}

app/blueprints/problems/templates/problems/base.html
{% extends "base.html" %}

{% block css %}
    <link rel="stylesheet" href="{{ url_for('problems.static', filename='css/task.css') }}">
    <link rel="stylesheet" href="{{ url_for('problems.static', filename='css/sidebar.css') }}">
{% endblock %}

{% block js %}
    <script type="module" src="{{ url_for('problems.static', filename='js/task.js') }}"></script>
{% endblock %}

{% block content %}
    <div class="container-fluid">
        <div class="row">
            {# Sidebar #}
            <div class="box-shadow sidebar col-xl-2" id="sidebar">
                <h3 class="sidebar__title"><i class="sidebar__title__icon fas fa-tasks"></i> Задачи:</h3>
                <ul class="nav sidebar_nav">
                    {% for sidebar_task in topic.tasks %}
                        {% if sidebar_task.id == task.id %}
                            {% set is_active = 'active_task' %}
                        {% endif %}

                        <li class="sidebar__item {{ is_active }}">
                            <a href="{{ sidebar_task.url() }}"
                               class="item__link">{{ sidebar_task.name }}</a>
                        </li>
                    {% endfor %}
                </ul>
            </div>
            {# Content #}
            <div class="task__main col-xl-8" id="task__main">
                {% block task_content %}{% endblock %}
            </div>
        </div>
    </div>
{% endblock %}

app/blueprints/problems/templates/problems/grade.html
{% extends "base.html" %}

{% block css %}
    <link rel="stylesheet" href="{{ url_for('problems.static', filename='css/grade.css') }}">
    <link rel="stylesheet" href="{{ url_for('problems.static', filename='css/route.css') }}">
{% endblock %}

{% block content %}
    <div class="container-fluid">
        <div class="row">
            <div class="route__body">
                <div class="route__title text_with_icon">
                    <i class="fa fa-2x fa-tasks route__title__icon" aria-hidden="true"></i>
                    <p class="route__title__text">Темы:</p>
                </div>
                {% if topics %}
                    <div class="route__body_list box-shadow">
                        {% for topic in topics %}
                            <div class="list_item">
                                <a href="{{ url_for(
                            'problems.topic_page',
                            grade_number=grade.number,
                            topic_translit_name=topic.translit_name
                            ) }}"
                                   class="list_item__link"></a>
                                <div class="list_item_content">
                                    <p class="item_title">{{ topic.name }}</p>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                {% else %}
                    {% include 'responses/empty_response.html' %}
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}

app/blueprints/problems/templates/problems/problem.html
{% extends 'problems/base.html' %}

{% block css %}
    {{ super() }}
    {% include 'codemirror/css.html' %}
    <link rel="stylesheet" href="{{ url_for('problems.static', filename='css/loader.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/editor.css') }}">
{% endblock %}

{% block js %}
    {{ super() }}
    {#  Codemirror.js  #}
    {% include 'codemirror/init.html' %}
    {# == Mods == #}
    {% include 'codemirror/mods.html' %}
    {#  == Addons == #}
    {% include 'codemirror/addons.html' %}
    {#  Addons/fold  #}
    {% include 'codemirror/fold.html' %}

    <script type="module" src="{{ url_for('static', filename='js/editor.js') }}"></script>
{% endblock %}

{% block task_content %}
    <div class="tabs">
        <ul class="nav nav-tabs" id="task_tabs" role="tablist">
            <li class="nav-item">
                <a href="{{ task.url() }}" class="nav-link active" id="task-tab" role="tab"
                   aria-selected="true">Задача</a>
            </li>
            <li class="nav-item">
                <a href="{{ task.url(tab='submissions') }}" class="nav-link hide_after" id="submissions-tab"
                   role="tab"
                   aria-selected="false">Мои отправки</a>
            </li>
        </ul>
    </div>
    <div class="task" id="task">
        <div class="task__header box-shadow">
            <div class="task__header__buttons">
                {% if current_user.is_admin %}
                    <a href="{{ url_for('admin.edit_task_page', id=task.id) }}" data-tooltip="tooltip"
                       data-placement="top" title="Изменить задачу"
                       class="default_button header__button" id="report_task__btn">
                        <i class="default_button__icon fas fa-pen"></i>
                    </a>

                    <button data-toggle="modal" data-target="#deleteModal"
                            data-tooltip="tooltip" data-placement="top" title="Удалить задачу"
                            class="alert_button header__button" id="report_task__btn">
                        <i class="default_button__icon far fa-trash-alt"></i>
                    </button>
                {% endif %}
                <button data-toggle="modal" data-target="#reportModal"
                        data-tooltip="tooltip" data-placement="top" title="Пожаловаться на задачу"
                        class="alert_button" id="report_task__btn">
                    <i class="default_button__icon fas fa-exclamation-triangle"></i>
                </button>
            </div>
            <p class="task__title">{{ task.name }}</p>
            <div class="task__condition task__header__block">
                <h4 class="condition__title task__sub_title">Условие</h4>
                <p class="condition__text">
                    {% for line in task.text.split('\n') %}
                        {{ line }}
                        {% if not loop.last %}
                            <br>
                        {% endif %}
                    {% endfor %}
                </p>
                {# Сюда вставить картинку #}
            </div>

            {% set example = task.example %}
            {% if example %}
                <div class="task__example task__header__block">
                    <h4 class="example__title task__sub_title">Пример</h4>
                    <div class="input">
                        <p class="example__subtitle">Ввод:</p>
                        <pre>
                        {% for input_line in example.example_input.split('\n') %}
                            <span>{{ input_line }}</span>
                        {% endfor %}
                    </pre>
                    </div>
                    <div class="output">
                        <p class="example__subtitle">Вывод:</p>
                        <pre>
                        {% for output_line in example.example_output.split('\n') %}
                            <span>{{ output_line }}</span>
                        {% endfor %}
                    </pre>
                    </div>
                </div>
            {% endif %}
        </div>


        <div class="task__body box-shadow">
            {# Editor #}
            <div class="editor">
                <div class="editor__header">
                    <div class="header__left_side">
                        <p class="dropdown__title">Язык:</p>
                        <div class="dropdown box-shadow">
                            <button class="btn btn-secondary dropdown-btn" type="button"
                                    id="dropdownMenuButton"
                                    data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                                <span class="languageDropdownButton__text"
                                                      id="languageDropdownButton__text">Python 3</span>
                                <span class="arrow">
                                <span></span><span></span>
                            </span>
                            </button>
                            <div class="dropdown-menu" id="dropdownMenuLanguage"
                                 aria-labelledby="dropdownMenuButton">
                                {% for key, language in language_dict.items() %}
                                    {% if language.is_default %}
                                        {% set is_active = 'active' %}
                                    {% else %}
                                        {% set is_active = '' %}
                                    {% endif %}

                                    <a class="dropdown-item {{ is_active }}" data-value="{{ key }}"
                                       data-mode="{{ language.mode }}">
                                        {{ language.name }}
                                    </a>
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                    <div class="header__right_side">
                        <div class="dropdown box-shadow">
                            <button class="btn btn-secondary dropdown-btn" type="button"
                                    id="dropdownMenuClassmateButton"
                                    data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                                <span class="classmateDropdownButton__text"
                                                      id="classmateDropdownButton__text">
                                                    Выберите напарника
                                                </span>
                                <span class="arrow">
                                <span></span><span></span>
                            </span>
                            </button>
                            <div class="dropdown-menu" id="dropdownMenuClassmate"
                                 aria-labelledby="dropdownMenuClassmateButton">
                                <h6 class="dropdown-header">Одноклассники:</h6>
                                {% for classmate in current_user.classmates %}
                                    <a class="dropdown-item {{ is_active }}"
                                       data-id="{{ classmate.id }}"
                                       data-fullname="{{ classmate.surname }} {{ classmate.name }}">
                                        {{ classmate.surname }} {{ classmate.name }}
                                    </a>
                                {% endfor %}
                            </div>
                        </div>

                        <button data-tooltip="tooltip" data-placement="top" title="Удалить код"
                                class="header__button alert_button" id="reset-code__btn">
                            <i class="default_button__icon far fa-trash-alt"></i>
                        </button>
                        <button data-tooltip="tooltip" data-placement="top" title="Скопировать код"
                                class="header__button default_button" id="copy-code__btn">
                            <i class="default_button__icon far fa-copy"></i>
                        </button>
                    </div>
                </div>
                <div class="editor__body" id="editor__body"></div>
                <div class="editor__footer">
                    <button class="submit-code__btn" id="submit-code__btn">Отправить</button>
                </div>
                <div class="code-response">
                    <div class="code-response__loader" id="code-response__loader">
                        <div class="lds-roller">
                            <div></div>
                            <div></div>
                            <div></div>
                            <div></div>
                            <div></div>
                            <div></div>
                            <div></div>
                            <div></div>
                        </div>
                    </div>
                    <div class="code-response__body" id="code-response__body">
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block modals %}
    {# Report task Modal #}
    <div class="modal fade" id="reportModal" tabindex="-1" role="dialog"
         aria-labelledby="reportModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="reportModalLabel">Пожаловаться</h5>
                    <button type="button" class="close" data-dismiss="modal"
                            aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <form id="report_form" method="post" role="form">
                    <div class="modal-body">
                        <div class="form__content">
                            <p class="form__title">Опишите проблему:</p>
                            <textarea class="modal_textarea" id="report_text" required
                                      placeholder="Описание"></textarea>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary"
                                data-dismiss="modal">Закрыть
                        </button>
                        <input class="btn btn-success" id="send_report"
                               name="submit" type="submit" value="Отправить">
                    </div>
                </form>
            </div>
        </div>
    </div>
    {% if current_user.is_admin %}
        {# Delete task Modal #}
        <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog"
             aria-labelledby="deleteModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="deleteModalLabel">Подтверждение действия</h5>
                        <button type="button" class="close" data-dismiss="modal"
                                aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <p class="form__title">Вы уверены, что хотите удалить задание?</p>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary"
                                data-dismiss="modal">Закрыть
                        </button>
                        <button type="button" id="deleteTaskButton" class="btn btn-danger"
                                data-taskID="{{ task.id }}">
                            Удалить
                        </button>
                    </div>
                </div>
            </div>
        </div>
    {% endif %}
{% endblock %}

app/blueprints/problems/templates/problems/submissions.html
{% extends 'problems/base.html' %}

{% block css %}
    {{ super() }}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/table.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/submissions_table.css') }}">
{% endblock %}

{% block task_content %}
    <div class="tabs">
        <ul class="nav nav-tabs" id="task_tabs" role="tablist">
            <li class="nav-item">
                <a href="{{ task.url() }}" class="nav-link" id="task-tab" role="tab" aria-selected="false">
                    Задача
                </a>
            </li>
            <li class="nav-item">
                <a href="{{ task.url(tab='submissions') }}" class="nav-link active hide_after"
                   id="submissions-tab" role="tab" aria-selected="true">
                    Мои отправки
                </a>
            </li>
        </ul>
    </div>
    <div class="submissions" id="submissions">
        <div class="submissions__body" id="submissions__body">
            {% include 'responses/submissions_table.html' %}
        </div>
    </div>
{% endblock %}

app/blueprints/problems/templates/problems/tabs/all_submissions.html
{% extends 'problems/base.html' %}

{% block css %}
    {{ super() }}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/table.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/submissions_table.css') }}">
{% endblock %}

{% block task_content %}
    <div class="tabs">
        <ul class="nav nav-tabs" id="task_tabs" role="tablist">
            <li class="nav-item">
                <a href="{{ task.url() }}" class="nav-link" id="task-tab" role="tab" aria-selected="false">
                    Задача
                </a>
            </li>
            <li class="nav-item">
                <a href="{{ task.url(tab='submissions') }}" class="nav-link"
                   id="submissions-tab" role="tab" aria-selected="false">
                    Мои отправки
                </a>
            </li>
            {% if current_user.is_admin %}
                <li class="nav-item">
                    <a href="{{ task.url(tab='all-submissions') }}" class="nav-link active"
                       id="submissions-tab" role="tab" aria-selected="true">
                        Все отправки
                    </a>
                </li>
            {% endif %}
        </ul>
    </div>
    <div class="submissions" id="submissions">
        <div class="submissions__body" id="submissions__body">
            {% include 'responses/submissions_table.html' %}
        </div>
    </div>
{% endblock %}

app/blueprints/problems/templates/problems/tabs/submissions.html
{% extends 'problems/base.html' %}

{% block css %}
    {{ super() }}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/table.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/submissions_table.css') }}">
{% endblock %}

{% block task_content %}
    <div class="tabs">
        <ul class="nav nav-tabs" id="task_tabs" role="tablist">
            <li class="nav-item">
                <a href="{{ task.url() }}" class="nav-link" id="task-tab" role="tab" aria-selected="false">
                    Задача
                </a>
            </li>
            <li class="nav-item">
                <a href="{{ task.url(tab='submissions') }}" class="nav-link active"
                   id="submissions-tab" role="tab" aria-selected="true">
                    Мои отправки
                </a>
            </li>
            {% if current_user.is_admin %}
                <li class="nav-item">
                    <a href="{{ task.url(tab='all-submissions') }}" class="nav-link"
                       id="submissions-tab" role="tab" aria-selected="false">
                        Все отправки
                    </a>
                </li>
            {% endif %}
        </ul>
    </div>
    <div class="submissions" id="submissions">
        <div class="submissions__body" id="submissions__body">
            {% include 'responses/submissions_table.html' %}
        </div>
    </div>
{% endblock %}

app/blueprints/problems/templates/problems/task_base.html
{% extends "base.html" %}

{% block css %}
    <link rel="stylesheet" href="{{ url_for('problems.static', filename='css/task.css') }}">
    <link rel="stylesheet" href="{{ url_for('problems.static', filename='css/sidebar.css') }}">
{% endblock %}

{% block js %}
    <script type="module" src="{{ url_for('problems.static', filename='js/task.js') }}"></script>
{% endblock %}

{% block content %}
    <div class="container-fluid">
        <div class="row">
            {# Sidebar #}
            <div class="box-shadow sidebar col-xl-2" id="sidebar">
                <h3 class="sidebar__title"><i class="sidebar__title__icon fas fa-tasks"></i> Задачи:</h3>
                <ul class="nav sidebar_nav">
                    {% for sidebar_task in topic.tasks %}
                        {% if sidebar_task.id == task.id %}
                            {% set is_active = 'active_task' %}
                        {% endif %}

                        <li class="sidebar__item {{ is_active }}">
                            <a href="{{ get_task_url(sidebar_task) }}"
                               class="item__link">{{ sidebar_task.name }}</a>
                        </li>
                    {% endfor %}
                </ul>
            </div>
            {# Content #}
            <div class="task__main col-xl-8" id="task__main">
                {% block task_content %}{% endblock %}
            </div>
        </div>
    </div>
{% endblock %}

app/blueprints/problems/templates/problems/task_submissions.html
{% extends 'problems/task_base.html' %}

{% block css %}
    {{ super() }}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/table.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/submissions_table.css') }}">
{% endblock %}

{% block task_content %}
    <div class="tabs">
        <ul class="nav nav-tabs" id="task_tabs" role="tablist">
            <li class="nav-item">
                <a href="{{ get_task_url(task) }}" class="nav-link" id="task-tab" role="tab" aria-selected="false">
                    Задача
                </a>
            </li>
            <li class="nav-item">
                <a href="{{ get_task_url(task, tab='submissions') }}" class="nav-link active hide_after"
                   id="submissions-tab" role="tab" aria-selected="true">
                    Мои отправки
                </a>
            </li>
        </ul>
    </div>
    <div class="submissions" id="submissions">
        <div class="submissions__body" id="submissions__body">
            {% include 'responses/submissions_table.html' %}
        </div>
    </div>
{% endblock %}

app/blueprints/problems/templates/problems/topic.html
{% extends "base.html" %}

{% block css %}
    <link rel="stylesheet" href="{{ url_for('problems.static', filename='css/route.css') }}">
{% endblock %}

{% block content %}
    <div class="container-fluid">
        <div class="row">
            <div class="route__body">
                <div class="route__header">
                    <div class="route__title text_with_icon">
                        <i class="fa fa-2x fa-tasks route__title__icon" aria-hidden="true"></i>
                        <p class="route__title__text">Задачи:</p>
                    </div>
                    {% if current_user.role.name == 'admin' %}
                        <a href="{{ url_for('admin.edit_topic_page', id=topic.id) }}" data-tooltip="tooltip"
                           data-placement="top"
                           title="Изменить тему"
                           class="default_button">
                            <i class="default_button__icon fas fa-pen"></i>
                        </a>
                    {% endif %}
                </div>
                {% if tasks %}
                    <div class="route__body_list box-shadow">
                        {% for task in tasks %}
                            <div class="list_item">
                                <a href="{{ task.url() }}" class="list_item__link"></a>
                                <div class="list_item_content">
                                    <p class="item_title">{{ task.name }}</p>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                {% else %}
                    {% include 'responses/empty_response.html' %}
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}